doc: known issue selecting stack during install
pivotal-cf/docs-csb-aws pull request #265
Opened 2023-07-26 10:51 UTC by fnaranjo-vmw

[#185675276]

When there are multiple build packs installed and non of them is a cflinuxfs4 , when creating the droplet for the tile with the default stack, CF will just take the first matching one.

But if both Windows and Linux have installed the binary_buildpack, it can happen that it matches a Windows buildpack.

Which other branches should this be merged with (if any)? none

2023-07-26 17:13 UTC, zucchinidev requested changes

2023-07-27 06:53 UTC, fnaranjo-vmw commented on release-notes.html.md.erb
> +
Great point. Can you suggest a way to rephrase this?
I just copied the description present in the Tracket story AS-IS.

2023-07-27 06:59 UTC, fnaranjo-vmw commented
Related work:
- https://github.com/pivotal/cloud-service-broker-tile-aws/pull/43
- https://github.com/pivotal/cloud-service-broker-tile-azure/pull/20
- https://github.com/pivotal/cloud-service-broker-tile-gcp/pull/27
- https://github.com/pivotal-cf/docs-csb-aws/pull/262
- https://github.com/pivotal-cf/docs-csb-azure/pull/107
- https://github.com/pivotal-cf/docs-csb-gcp/pull/113/commits/c98aa34634f42d790076af4ccd6d8609c7d635ee
- https://github.com/pivotal-cf/docs-csb-azure/pull/108
- https://github.com/pivotal-cf/docs-csb-gcp/pull/114
- https://github.com/pivotal-cf/docs-csb-aws/pull/265

2023-07-27 16:13 UTC, fnaranjo-vmw commented on release-notes.html.md.erb
> +  it matches a Windows buildpack if both Windows and Linux have installed the binary_buildpack.
Hey Andrea, thanks for the time rethinking this, but notice that this is in the **Known Issues** section.
I believe your suggestion doesn't account for that.

2023-07-28 00:10 UTC, HenryBorys commented on release-notes.html.md.erb
> +  it matches a Windows buildpack if both Windows and Linux have installed the binary_buildpack.
@fnaranjo-vmw @zucchinidev Is everyone good to go with: "Incorrect buildpack stack association when the stack `cflinuxfs4` is not available in your deployment."? Thanks!

2023-07-28 10:12 UTC, zucchinidev approved these changes

2023-07-28 10:13 UTC, pivotal-marcela-campo commented on release-notes.html.md.erb
> +  it matches a Windows buildpack if both Windows and Linux have installed the binary_buildpack.
Hi @HenryBorys , we updated the PR. It looks good now. Ready to merge.

2023-07-28 19:30 UTC, merged