postgres: document binding known issue and workarounds
pivotal-cf/docs-csb-aws pull request #272
Opened 2023-07-26 15:10 UTC by pivotal-marcela-campo

Which other branches should this be merged with (if any)? 1.5, 1.4

2023-07-27 09:44 UTC, fnaranjo-vmw requested changes

2023-07-27 09:44 UTC, fnaranjo-vmw commented on troubleshooting.html.md.erb
> +### <a id="posrgres-errors"></a> Amazon PostgreSQL errors
```suggestion
### <a id="postgres-errors"></a> Amazon PostgreSQL errors
```

Fix errata.

2023-07-27 09:44 UTC, fnaranjo-vmw commented on troubleshooting.html.md.erb
> +                <td>Bindings modifyig/reading tables created by other bindings</td>
```suggestion
                <td>Bindings modifying/reading tables created by other bindings</td>
```
Fix errata.

2023-07-27 09:44 UTC, fnaranjo-vmw commented on troubleshooting.html.md.erb
> +                  and hence the only one able to modify tables and query them, unless permission is explicitely give to other
```suggestion
                  and hence the only one able to modify tables and query them, unless permission is explicitly granted to other 
```

2023-07-27 09:44 UTC, fnaranjo-vmw commented on troubleshooting.html.md.erb
> +                    </ul>
```suggestion
                       <li>Binding A not being able to change tables created by binding B in PUBLIC schema, until a new binding C gets created</li>
                    </ul>
```

2023-07-27 09:44 UTC, fnaranjo-vmw commented on troubleshooting.html.md.erb
> +                2. Manuall transfer ownership to the binding_user_group with the following statement "ALTER TABLE tab_name OWNER TO binding_user_group;".
```suggestion
                2. Manually transfer ownership to the binding_user_group with the following statement "ALTER TABLE tab_name OWNER TO binding_user_group;". 
```

2023-07-27 09:44 UTC, fnaranjo-vmw commented on troubleshooting.html.md.erb
> +                This is because the CSB does assign permissions to all existing tables whenever a new binding is created. However this new bindings will still
```suggestion
                This is because the CSB does assign permissions to all existing tables in the PUBLIC schema whenever a new binding is created. However this new bindings will still 
```

2023-07-27 09:44 UTC, fnaranjo-vmw commented on troubleshooting.html.md.erb
> +                3. If you only need other bindings to perform data operations, then you can create new bindings for interacting with these objects.
```suggestion
                3. If you only need other bindings to perform data operations in tables from the PUBLIC schema, then you can create new bindings for interacting with these objects.
```

2023-07-27 10:16 UTC, pivotal-marcela-campo commented on troubleshooting.html.md.erb
> +                    </ul>
I'll take your suggestion, but I still need two separate scenarios as one refers to read/write data and the other to table schema manipulation. I'll make that clearer.

2023-07-27 11:49 UTC, fnaranjo-vmw commented on troubleshooting.html.md.erb
> +                    </ul>
I updated my suggestion. In fact, after creating a new binding I believe it is still unable to change tables created by binding B.

So your concern about my feedback was legitimate, but in reality we only need 1 scenario.

2023-07-27 13:12 UTC, pivotal-marcela-campo commented on troubleshooting.html.md.erb
> +                    </ul>
yes, another binding cannot do alter table until the original binding is deleted. Depending on the use case, customers may want to delete the original binding to fix things, or they might be okay with just creating a new binding to provide read/write access to tables. That's why I decided to split it in 2.  In fact after your suggestion I added a third scenario, which is in fact the same issue, but a different symptom, focusing more in what the user is seeing and less in the underlying cause.

2023-07-28 10:20 UTC, zucchinidev approved these changes

2023-07-28 20:01 UTC, merged