doc: creating a publicly_accessible rds
pivotal-cf/docs-csb-aws pull request #276
Opened 2023-08-01 08:01 UTC by fnaranjo-vmw

[#185332477]

Which other branches should this be merged with (if any)? none

2023-08-01 08:06 UTC, fnaranjo-vmw commented
Most probably we need to move this file to a different location in the repo and link it somehow for it to appear in the menu.

Also, we may want to duplicate this guide in GCP and Azure, or even better, remove any step unrelated to AWS and move it to the corresponding docs for another IAAS.

If we go the extra mile of duplicating this guide for every RDS service, linking it in the appropriate section becomes easier, at the cost of duplication.

Another good reason against duplicating this guide for each RDS service is that RDS services are extremely similar, so adding specific details for each service (if any) won't provide much more clarity.

2023-08-01 16:33 UTC, zucchinidev requested changes

2023-08-01 16:33 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +## Pitfalls when creating service plans
thoughts: I’m not sure if this applies here. We are assuming that the configuration of virtual networks and subnets is not correct because our CloudFoundry environment creates a configuration that does not fit well with public networks, but we cannot assume the same in the installations of customers.

2023-08-01 16:33 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +This is strictly true for AWS RDS. Other IAASes use different naming conventions (GCP > public_ip),
thoughts: I wouldn’t mention GCP and public ip. It doesn’t apply to this product and it doesn’t look like we’re going to create a partial view of this, at least that’s not the initial goal

2023-08-01 16:33 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +  _Failing to do this can confuse consumers of your plan if they set `publicly_accessible: true` and still can't connect to the DB._
thoughts: networks and subnets can be modified, however if a plan is created with this property, the value cannot be modified. I would not add this sentence or if I did, it would be a recommendation

2023-08-01 16:33 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +- If setting `publicly_accessible: true` or `ipv4_enabled: true` doesn't seem to allow public connections, contact the team
nit-pick: remove GCP configuration

2023-08-01 16:33 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +  in charge of creating the CSB plans for your org and ask them whether they intend to support public database instances or not.
nit-pick: the plan may not be related to the fact that the instance does not support public connections, therefore it would not add the suggestion to contact the team in charge of creating plans. We must remember that customers are either developers or operators

2023-08-01 16:33 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +- If your service uses GCP SQL, you should specify `authorized_networks_cidrs` as a JSON array of CIDR notation IPv4 or IPv6 addresses.
nit-pick: this sentence does not apply

2023-08-01 16:33 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +  _You will need access to AWS Console to create the security groups. Alternatively, ask your CSB operators to provide you this list._
I would suggest checking that the rules created in the security rule are adequate

2023-08-01 16:33 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +     _You should skip **Step 4: Create a DB instance in the VPC** since we want the DB to be managed by CSB._
nit-pick: if we mention the step number and the order of the AWS documentation changes, we will have an outdated documentation

2023-08-01 16:33 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +  1. [Create a CSB instance.](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-AWS/1.5/csb-aws/GUID-reference-index.html)
nit-pick: use a correct link structure

2023-08-01 16:33 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +     `aws_vpc_id`, `rds_subnet_group`, `rds_vpc_security_group_ids`, `publicly_accessible`.
thoughts: this is not quite correct, the default network may have all the correct subnets and security rules to support instances with public access

2023-08-01 16:33 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +     `authorized_network_id`, `authorized_networks_cidrs` and `public_ip`.
nit-pick: delete the GCP references

2023-08-01 17:15 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +## Pitfalls when creating service plans
> Pitfall: a hidden or unsuspected danger or difficulty.

I don't see why it wouldn't fit in this guide.
Isn't this guide precisely to help customers and ourselves set up public databases correctly (when needed?)

Isn't this section describing a real and non-obvious behaviour of our product?

The section begins with the text:
- Remember to explicitly specify a VPC and subnet group in your plan **(unless you have strong reason not to)**.

Is the following affirmations wrong or misleading?
> can lead to **unexpected** and **unpredictable** network configurations

I believe **unpredictable** to be the exact description for something that is unspecified.
If a customer doesn't **specify a VPC and subnet group in [their] plan** that's exactly what **could** happen.

2023-08-01 17:15 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +This is strictly true for AWS RDS. Other IAASes use different naming conventions (GCP > public_ip),
Create a code suggestion please, so I can accept it and merge it easily.

2023-08-01 17:15 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +  _Failing to do this can confuse consumers of your plan if they set `publicly_accessible: true` and still can't connect to the DB._
Create a code suggestion please, so I can accept it and merge it easily.

2023-08-01 17:15 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +- If setting `publicly_accessible: true` or `ipv4_enabled: true` doesn't seem to allow public connections, contact the team
Create a code suggestion please, so I can accept it and merge it easily.

2023-08-01 17:16 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +  _You will need access to AWS Console to create the security groups. Alternatively, ask your CSB operators to provide you this list._
Create a code suggestion please, so I can accept it and merge it easily.

2023-08-01 17:16 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +     _You should skip **Step 4: Create a DB instance in the VPC** since we want the DB to be managed by CSB._
Create a code suggestion please, so I can accept it and merge it easily.

2023-08-01 17:16 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +  1. [Create a CSB instance.](https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-AWS/1.5/csb-aws/GUID-reference-index.html)
Create a code suggestion please, so I can accept it and merge it easily.

2023-08-01 17:20 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +     `aws_vpc_id`, `rds_subnet_group`, `rds_vpc_security_group_ids`, `publicly_accessible`.
It is not guaranteed though. And adding new subnets in the default network might have unexpected and unpredictable consequences.
Still this guide **suggests** `to explicitly specify a VPC and subnet group in your plan (unless you have strong reason not to). ` But leaves the door open if you know what you are doing and have strong reasons to do it that way.

I see this guide as a resource for people not knowing how to proceed.
This guide is not for those who know what to do and have strong opinions on how to do it.
In fact, those people won't expose the database directly. They will probably create a bastion host:
https://repost.aws/knowledge-center/rds-connect-using-bastion-host-linux

2023-08-01 17:21 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +     `authorized_network_id`, `authorized_networks_cidrs` and `public_ip`.
Create a code suggestion please, so I can accept it and merge it easily.

2023-08-01 17:21 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-AWS/1.5/csb-aws/GUID-reference-aws-postgres.html#configuration-parameters-1
Create a code suggestion please, so I can accept it and merge it easily.

2023-08-02 16:44 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +- If your service uses GCP SQL, you should specify `authorized_networks_cidrs` as a JSON array of CIDR notation IPv4 or IPv6 addresses.
Create a code suggestion please, so I can accept it and merge it easily.

2023-08-02 16:44 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +  in charge of creating the CSB plans for your org and ask them whether they intend to support public database instances or not.
Create a code suggestion please, so I can accept it and merge it easily.

2023-08-03 16:07 UTC, zucchinidev requested changes

2023-08-03 16:07 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +  _You will need access to AWS Console to create the security groups. Alternatively, ask your CSB operators to provide you this list._
```suggestion
  _You may need to review your security rules to add the rules needed to allow network traffic._
```

2023-08-03 16:07 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +     _You should skip **Step 4: Create a DB instance in the VPC** since we want the DB to be managed by CSB._
```suggestion
    _You should skip **The "Create a DB instance in the VPC" step** since we want the DB to be managed by CSB._
```

2023-08-03 16:07 UTC, zucchinidev commented on howtos/publicly-accessible-dbs.md
> +     `aws_vpc_id`, `rds_subnet_group`, `rds_vpc_security_group_ids`, `publicly_accessible`.
Hi @fnaranjo-vmw , feel free to ignore my thoughts. They are non-blocking.
Just a kind reminder, the product is use by developers and operators. A certain knowledge is presupposed.

2023-08-03 16:21 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +This is strictly true for AWS RDS. Other IAASes use different naming conventions (GCP > public_ip),
```suggestion
```

2023-08-03 16:23 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +the DB instance public.
```suggestion
Setting `publicly_accessible` is required but not sufficient for making the DB instance public.
```

2023-08-04 10:13 UTC, pivotal-marcela-campo commented on howtos/publicly-accessible-dbs.md
> +## Pitfalls when creating service plans
@fnaranjo-vmw @zucchinidev Just for context:  "the more so
given that for some services you can also leave the VPC unspecified. CSB will pick the default one."

I think we missed something here that is the fact that in AWS service broker tile configuration there is a specific field for VPC_ID that is mandatory. So VPC_ID parameter will never be empty for tile users (customers). It is true though that for open source users that deploy by doing `cf push`, this field wouldn't be required. Applications wouldn't be able to connect to the service instances created though as they are in a different VPC (TAS VPC vs default VPC) and they would have a much more greater issue than just making a database public.

2023-08-04 10:13 UTC, pivotal-marcela-campo commented on howtos/publicly-accessible-dbs.md
> +  _Failing to do this can confuse consumers of your plan if they set `publicly_accessible: true` and still can't connect to the DB._
VPC is specified at a broker level

2023-08-04 17:14 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +  _Failing to do this can confuse consumers of your plan if they set `publicly_accessible: true` and still can't connect to the DB._
Thanks Marcella.

Is it impossible to override the VPC in the plan? If so, I'll need to make some changes in the troubleshooting page.

2023-08-04 17:25 UTC, fnaranjo-vmw commented on troubleshooting.html.md.erb
> +                        <li>Check if explicitly specifying `aws_vpc_id`, `rds_subnet_group` and `rds_vpc_security_group_ids` solves the issue.</li>
```suggestion
                        <li>Check if explicitly specifying <code>aws_vpc_id</code>, <code>rds_subnet_group</code> and <code>rds_vpc_security_group_ids</code> solves the issue.</li>
```

2023-08-04 22:59 UTC, zucchinidev approved these changes
Great job @fnaranjo-vmw !! I am sure I will use this page many times when configuring the publicly accesible instance

2023-08-04 22:59 UTC, zucchinidev commented on troubleshooting.html.md.erb
> +                          <i>Pitfall: according to AWS official docs, <quote>for a DB instance to be publicly accessible, all of the subnets in its DB subnet group must be public.</quote></i>
praise: great! I love it

2023-08-07 10:27 UTC, fnaranjo-vmw commented on howtos/publicly-accessible-dbs.md
> +  _Failing to do this can confuse consumers of your plan if they set `publicly_accessible: true` and still can't connect to the DB._
[In this commit](https://github.com/pivotal-cf/docs-csb-aws/pull/276/commits/c10367bed34f5f0a2933411acab65530c283184e) I rephrased most of the pitfalls to address @pivotal-marcela-campo concern.

2023-08-07 10:40 UTC, pivotal-marcela-campo requested changes

2023-08-07 10:40 UTC, pivotal-marcela-campo commented on troubleshooting.html.md.erb
> +                          Pitfall: when <code>rds_subnet_group</code> is left blank the service instance is associated to whatever subnet group is specified in the Tile's config.<br>
```suggestion
                          Pitfall: when <code>rds_subnet_group</code> is left blank the service instance is associated to whatever subnet group is specified in the Tile's Service Offering config if present.<br>
```

2023-08-07 10:40 UTC, pivotal-marcela-campo commented on troubleshooting.html.md.erb
> +                          Pitfall: when <code>rds_vpc_security_group_ids</code> is left blank the service instance is associated to whatever subnet group is specified in the Tile's config.<br>
```suggestion
                          Pitfall: when <code>rds_vpc_security_group_ids</code> is left blank the service instance is associated to whatever subnet group is specified in the Tile's Service Offering config if present.<br>
```

2023-08-07 10:40 UTC, pivotal-marcela-campo commented on troubleshooting.html.md.erb
> +                  For service plans creators:
```suggestion
                  For operators:
```

2023-08-07 10:40 UTC, pivotal-marcela-campo commented on troubleshooting.html.md.erb
> +                          Explicitly specify <code>aws_vpc_id</code>, <code>rds_subnet_group</code> and <code>rds_vpc_security_group_ids</code> in the plan.<br>
```suggestion
                          Explicitly specify <code>aws_vpc_id</code>, <code>rds_subnet_group</code> and <code>rds_vpc_security_group_ids</code> in the plans or specify a default value in the Service Offering configuration when option is present.<br>
```

2023-08-07 10:40 UTC, pivotal-marcela-campo commented on troubleshooting.html.md.erb
> +                        <li>Set <code>publicly_accessible: false</code> if your VPC, subnets and security groups are not designed with public DBs in mind or if you want to disallow them.</li>
```suggestion
                        <li>Set <code>publicly_accessible: false</code> in the plans if your VPC, subnets and security groups are not designed with public DBs in mind or if you want to disallow them.</li>
```

2023-08-07 11:48 UTC, pivotal-marcela-campo approved these changes

2023-08-14 21:37 UTC, merged