MSSQL: CloudWatch properties exposed
pivotal-cf/docs-csb-aws pull request #305
Opened 2023-09-12 16:31 UTC by zucchinidev

[#185202654](https://www.pivotaltracker.com/story/show/185202654)

Which other branches should this be merged with (if any)?

None

2023-09-13 15:46 UTC, fnaranjo-vmw requested changes

2023-09-13 15:46 UTC, fnaranjo-vmw commented on reference/aws-mssql.html.md.erb
> +        log group created for the `agent` and `error` logs.
```suggestion
        log group created for the <code>agent</code> and <code>error</code> logs.
```

2023-09-13 15:46 UTC, fnaranjo-vmw commented on reference/aws-mssql.html.md.erb
> +        When deactivated, the associated `agebt` CloudWatch log group is deleted.
```suggestion
        If <code>true</code>, it enables the <code>agent</code> <code>cloud_watch_log_export</code>
        on the RDS instance.
        When activated, it creates an associated <code>agent</code> CloudWatch log group.
        When deactivated, the associated <code>agent</code> CloudWatch log group is deleted.
```

2023-09-13 19:52 UTC, HenryBorys commented
@zucchinidev please review @fnaranjo-vmw 's requested changes and resolve conflicts, and then I'll merge. Thanks!

2023-09-14 09:57 UTC, zucchinidev commented
Thank you very much, @fnaranjo-vmw. Suggested changes accepted!
Thank you very much, @HenryBorys !! :rocket:

2023-09-14 18:27 UTC, merged