General: improve upgrade process guide
pivotal-cf/docs-csb-aws pull request #323
Opened 2023-10-03 13:59 UTC by zucchinidev

[#185853346](https://www.pivotaltracker.com/story/show/185853346)

Which other branches should this be merged with (if any)?

None

2023-10-03 14:21 UTC, pivotal-marcela-campo requested changes

2023-10-03 15:45 UTC, zucchinidev commented on upgrading.html.md.erb
> +   > You will have to reverse the started installation process.
Thank you very much @pivotal-marcela-campo

2023-10-03 22:01 UTC, HenryBorys commented
@pivotal-marcela-campo I'll merge once you've reviewed. Thanks. Actually, after today (the 3rd), I'll be on PTO till the 23rd, so @snneji will likely merge this.

2023-10-04 09:38 UTC, zucchinidev commented
Thank you very much @HenryBorys, @pivotal-marcela-campo . I convert the PR to draft because we found a problem in the new functionality and we need to find a solution.

2023-10-09 14:26 UTC, pivotal-marcela-campo approved these changes

2023-10-09 14:27 UTC, merged