Iops update issue
pivotal-cf/docs-csb-aws pull request #344
Opened 2024-03-05 11:51 UTC by pivotal-marcela-campo

Which other branches should this be merged with (if any)? 1.7

2024-03-05 15:23 UTC, zucchinidev approved these changes

2024-03-05 15:23 UTC, zucchinidev commented on troubleshooting.html.md.erb
> +                  Whilst creating instances with <code>"storage_type": "gp3"</code> and <code>"storage_gb" < 400GB</code> can be achieved by setting `iops: 0` as instructed in
```suggestion
                  Whilst creating instances with <code>"storage_type": "gp3"</code> and <code>"storage_gb" &lt; 400GB</code> can be achieved by setting `iops: 0` as instructed in 
```

2024-03-05 15:25 UTC, zucchinidev requested changes

2024-03-05 15:25 UTC, zucchinidev commented on troubleshooting.html.md.erb
> +                    conditions need to be created with <code>"iops": 0</code> and then updated or moved to a plan that specify <code>"iops": 3000</code> instead for further
question: do you want to say `need to be created with` or `need to be updated with`? the instances is already created

2024-03-05 15:29 UTC, pivotal-marcela-campo commented on troubleshooting.html.md.erb
> +                    conditions need to be created with <code>"iops": 0</code> and then updated or moved to a plan that specify <code>"iops": 3000</code> instead for further
> question: do you want to say `need to be created with` or `need to be updated with`? the instances is already created

They need to be created with `iops:0` otherwise it fails creation as per previous troubleshooting entry, then updated or moved to a plan with iops: 3000 otherwise they cannot be updated/upgraded anymore

2024-03-05 15:46 UTC, zucchinidev approved these changes

2024-03-05 17:20 UTC, merged

2024-03-05 21:27 UTC, HenryBorys commented
@pivotal-marcela-campo Should the additions to the Troubleshooting page also be merged into main, which will become 1.9?

2024-03-05 21:48 UTC, HenryBorys commented
@pivotal-marcela-campo Because this PR has changes to release notes for 1.8, I don't think it's a good idea to cherry pick to 1.7 and main (if you wanted it to be on main). I assume you wanted just the changes to Troubleshooting to go to 1.7 (and main?), right? If that's so, could you do a separate PR against main and instruct me to cherry pick to 1.7? Or let me know what you have in mind. Thanks.

2024-03-07 23:58 UTC, HenryBorys commented
@pivotal-marcela-campo I did add the updates to the Troubleshooting page in 1.7 and main, but made no changes to the release notes for either. I'll publish 1.7 and 1.8. If you want changes to the release notes for 1.7 or main, please make separate PRs for those. Thanks.