MySQL: expose storage_type, iops and deprecate cores
pivotal-cf/docs-csb-aws pull request #97
Opened 2022-09-29 10:55 UTC by zucchinidev

[#183023678](https://www.pivotaltracker.com/story/show/183023678)

Which other branches should this be merged with (if any)?

None

2022-09-29 16:45 UTC, FelisiaM requested changes

2022-09-29 16:45 UTC, FelisiaM commented on reference/aws-mysql.html.md.erb
> +| `storage_gb`*        | Size of storage volume for service instance. 5&ndash;4096.                            | 5         |
Worth changing the new default to 100 as well just to be consistent

2022-09-29 16:45 UTC, FelisiaM commented on release-notes.html.md.erb
> +- **the default storage type is now set as 'io1' (provisioned IOPS SSD):** Previously the default used
Need to add the service it relates to in the title. E.g `RDS MySQL new default storage type is provisioned IOPS SSD : ....`

2022-09-29 16:45 UTC, FelisiaM commented on release-notes.html.md.erb
> +- **`storage_type` and `iops` are configurable and updatable:** New added property that allows you to configure the
Maybe worth mentioning that default storage type is io1 if none is defined

2022-09-29 16:45 UTC, FelisiaM commented on release-notes.html.md.erb
> +  storage supported by the 'io1' storage type.
Can add a link to the "changing custom plans" page here

2022-09-29 16:45 UTC, FelisiaM commented on release-notes.html.md.erb
>  ### Features
A meta point for all the release notes - its worth putting all the MySQL related notes under the same bullet point with an increased indentation (so its clear these properties relate to Myssql and also Aurora release notes can also be distinctive) 

See example in previous release notes  https://docs.vmware.com/en/Tanzu-Cloud-Service-Broker-for-AWS/1.2/csb-aws/GUID-release-notes.html

2022-09-30 19:37 UTC, zucchinidev commented on release-notes.html.md.erb
>  ### Features
All fixed!! Thank you very much for your help!

2022-10-03 09:38 UTC, FelisiaM approved these changes

2022-10-03 09:51 UTC, merged

2022-10-03 09:51 UTC, RichardJJG commented
Thanks, @zucchinidev and @FelisiaM